// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtmuKtpYcRcyci8pAtIJa3_GrU9-urfy8',
    appId: '1:940918793229:web:f795b50be724bc41196144',
    messagingSenderId: '940918793229',
    projectId: 'food-dlivery-97e93',
    authDomain: 'food-dlivery-97e93.firebaseapp.com',
    storageBucket: 'food-dlivery-97e93.appspot.com',
    measurementId: 'G-FH4DSDHYVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1mp-P5qKynhSCaYZq_9NKWzxQCMKEMtQ',
    appId: '1:940918793229:android:b2e40aa6fb17bc79196144',
    messagingSenderId: '940918793229',
    projectId: 'food-dlivery-97e93',
    storageBucket: 'food-dlivery-97e93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYM7lWNDpy7j_trBsMG7WAiGTVdP_eAU',
    appId: '1:940918793229:ios:2bead168c744ea9e196144',
    messagingSenderId: '940918793229',
    projectId: 'food-dlivery-97e93',
    storageBucket: 'food-dlivery-97e93.appspot.com',
    iosClientId: '940918793229-mujh90ucvc90f70it4dv610ppp8vmios.apps.googleusercontent.com',
    iosBundleId: 'com.example.food',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYM7lWNDpy7j_trBsMG7WAiGTVdP_eAU',
    appId: '1:940918793229:ios:b6ec866f580284ae196144',
    messagingSenderId: '940918793229',
    projectId: 'food-dlivery-97e93',
    storageBucket: 'food-dlivery-97e93.appspot.com',
    iosClientId: '940918793229-o1sf7mc0777vl9t3r3ved0d9n5ei3hiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.food.RunnerTests',
  );
}
